name: SkyBlockGUI
main: CrazyTeamVN\SkyBlock\Main
version: 1.0.2
api: 3.0.0
author: CrazyTeamVN

commands:
 sbui:
  description: "Open SkyBlock Menu"
commands:
 is:
  description: "open skyblock Menu"
commands:
 sb:
  description: "open skyblock menu"
